version: 2.1

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.1

    working_directory: /go/src/github.com/AnuchitO/re
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
          command: |
            go get github.com/mattn/goveralls
            go test -v -covermode=count -coverprofile=coverage.out
            $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
