version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.1

    working_directory: /go/src/github.com/AnuchitO/re
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      # - run: go get -v -t -d ./...
      - run: go test -v ./...
