version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: go mod download
      - run:
          name: Vet
          command: go vet ./...
      - run:
          name: Test
          command: go test -v ./...
      - run:
          name: Coverage report
          command: |
            go test -covermode=count -coverprofile=coverage.out -v ./...
            go install github.com/mattn/goveralls@latest
            goveralls -coverprofile=coverage.out -service=circleci -repotoken $COVERALLS_TOKEN

workflows:
  build-and-test:
    jobs:
      - build
